### ISSUE TITLE
Switch the codebase in Typescript

### ISSUE THREAD

**Issue by cerisier** [SomebodyLikeEveryBody/MKAccrReplacer#1]
This tool can help ! https://github.com/airbnb/ts-migrate/tree/master/packages/ts-migrate
And this guide as well ! https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

**Comment by SomebodyLikeEveryBody** [comment]
Thank You Very Much !
I will start to work on that tonight
